host: 0.0.0.0
title: FreightForward Documentation
email: contact@resgef.com
description: >- # this means to ignore newlines until "baseurl:"
            Document Generator for Freight Forwarding Operations.
             Ocean Freight, Air Freight. Bill of Lading, Airway Bill, Delivery order, Shipment advice, Cargo Manifest, CFS Report, C&F Agents, Consolidation, Job Costing.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MinhajulAnwar
github_username: minhajme

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs #for gh-pages
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#https://pmarsceill.github.io/just-the-docs/docs/configuration/
search_enabled: false
aux_links:
  "FreightForward": https://github.com/minhajme/freightforward
  "Developer(Minhajul Anwar)": https://github.com/minhajme
  "Resgef Labs": https://resgef.com
aux_links_new_tab: true

ga_tracking: UA-202058120-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

#collections:
#  install:
#    permalink: "/:collection/:path/"
#    output: true
#  tutorials:
#    permalink: "/:collection/:path/"
#    output: true
#
#just_the_docs:
#  collections:
#    install:
#      name: Install Notes
#    tutorials:
#      name: Tutorials
